

// data types
export const SET_SHOW_TIME_OPEN = 'SET_SHOW_TIME_OPEN';
export const SET_SHOW_TIME_CLOSE = 'SET_SHOW_TIME_CLOSE';

export const SET_TIME_TODAY = 'SET_TIME_TODAY';
export const SET_TIME_5 = 'SET_TIME_5 ';
export const SET_TIME_10 = 'SET_TIME_10';

export const LOADING_DATA_TRUE = 'LOADING_DATA_TRUE';
export const LOADING_DATA_FALSE = 'LOADING_DATA_FALSE';

export const SET_ON_MARS_FALSE = 'SET_ON_MARS_FALSE';
export const SET_ON_MARS_TRUE = 'SET_ON_MARS_TRUE';

export const LOADING_MARS_POSTS_TRUE = 'LOADING_MARS_POSTS_TRUE';
export const LOADING_MARS_POSTS_FALSE = 'LOADING_MARS_POSTS_FALSE';

export const SET_ROVER_DATA = 'SET_ROVER_DATA';
export const SET_ROVER_NUM = 'SET_ROVER_NUM';

export const SET_ASTRONOMY_DATA = 'SET_ASTRONOMY_DATA';